name: 02 Crawler Scheduler II

on:
  repository_dispatch:
    types: [run-get-article]
  workflow_dispatch:

jobs:
  get-article-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout crawler-service branch
        uses: actions/checkout@v3
        with:
          ref: crawler-service
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r modules/news-crawler-service/requirements.txt

      - name: Run get-article command with retry
        id: get_article_run
        run: |
          n=0
          max_retries=100
          until [ $n -ge $max_retries ]
          do
            echo "Attempt $(($n+1)) of $max_retries: Running get-article..."
            if python modules/news-crawler-service/run.py get-article; then
              echo "Get-article run succeeded."
              break
            fi
            n=$(($n+1))
            echo "Get-article run failed. Retrying in 1 second..."
            sleep 1
          done
          if [ $n -ge $max_retries ]; then
            echo "Get-article failed after $max_retries attempts."
            exit 1
          fi

      - name: Trigger copy-article workflow
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "copy-article"}'

      - name: Trigger email alert for get-article result
        if: always()
        run: |
          WORKFLOW_FILE="02-crawler-scheduler-II.yml"
          if [ "${{ job.status }}" = "Success" ]; then
            ORIGINAL_SUBJECT="${WORKFLOW_FILE}: Get-article succeeded"
            CLASSIFICATION="Info"
            DETAIL="Result: The get-article command ran successfully."
          else
            ORIGINAL_SUBJECT="${WORKFLOW_FILE}: Get-article failed"
            CLASSIFICATION="Warn"
            DETAIL="Result: The get-article command encountered errors. Please check logs."
          fi
          FINAL_SUBJECT="Workflow Alert: ${CLASSIFICATION}"
          FINAL_BODY="${WORKFLOW_FILE}\n${ORIGINAL_SUBJECT}\n${DETAIL}"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d "{\"event_type\": \"send-email-alert\", \"client_payload\": {\"subject\": \"${FINAL_SUBJECT}\", \"body\": \"${FINAL_BODY}\"}}"
