name: 05-ai-summarize

on:
  repository_dispatch:
    types: [ai-summarize]
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  ai-summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r modules/news-crawler-service/requirements.txt
      
      - name: Run AI Summarize Command with Retry
        id: ai_summarize
        run: |
          n=0
          max_retries=100
          until [ $n -ge $max_retries ]
          do
            echo "Attempt $(($n+1)) of $max_retries: Running AI Summarize..."
            if python modules/news-crawler-service/run.py ai-summarize sk-1764cb54796444969843af67e8ac49e2 -o modules/news-crawler-service/src/output; then
              echo "AI Summarize succeeded."
              break
            fi
            n=$(($n+1))
            echo "AI Summarize failed. Retrying in 1 second..."
            sleep 1
          done
          if [ $n -ge $max_retries ]; then
            echo "AI Summarize failed after $max_retries attempts."
            exit 1
          fi
      
      - name: Set up Git identity
        run: |
          git config --global user.name "fox142857"
          git config --global user.email "fox142857@foxmail.com"

      - name: Commit AI Summarize Output
        run: |
          git add modules/news-crawler-service/src/output/
          if git diff --cached --exit-code; then
            echo "No changes to commit."
          else
            git commit -m "Update AI summarize output [skip ci]"
            git push origin master
          fi
      
      - name: Trigger Copy News Article workflow
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "copy-article"}'
      
      - name: Trigger email alert for AI Summarize result
        if: always()
        run: |
          WORKFLOW_FILE="05-ai-summarize.yml"
          if [ "${{ job.status }}" = "Success" ]; then
            ORIGINAL_SUBJECT="${WORKFLOW_FILE}: AI Summarize succeeded"
            CLASSIFICATION="Info"
            DETAIL="Result: The AI Summarize command ran successfully and output was updated."
          else
            ORIGINAL_SUBJECT="${WORKFLOW_FILE}: AI Summarize failed"
            CLASSIFICATION="Warn"
            DETAIL="Result: The AI Summarize command encountered errors. Please check logs."
          fi
          FINAL_SUBJECT="Workflow Alert: ${CLASSIFICATION}"
          FINAL_BODY="${WORKFLOW_FILE}\n${ORIGINAL_SUBJECT}\n${DETAIL}"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d "{\"event_type\": \"send-email-alert\", \"client_payload\": {\"subject\": \"${FINAL_SUBJECT}\", \"body\": \"${FINAL_BODY}\"}}"
