name: 06-copy-news-article

on:
  repository_dispatch:
    types: [copy-article]
  workflow_dispatch:

jobs:
  copy-article:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Determine source article file
        id: determine_src
        shell: bash
        run: |
          export TZ='Asia/Shanghai'
          TODAY=$(date +'%Y%m%d')
          YESTERDAY=$(date -d "yesterday" +'%Y%m%d')
          # 使用通配符匹配 YYYYMMDD-[四位数字]-ai-summarize.md 格式的文件
          SRC_TODAY=$(ls modules/news-crawler-service/src/output/${TODAY}-[0-9][0-9][0-9][0-9]-ai-summarize.md 2>/dev/null)
          SRC_YESTERDAY=$(ls modules/news-crawler-service/src/output/${YESTERDAY}-[0-9][0-9][0-9][0-9]-ai-summarize.md 2>/dev/null)
          echo "Today: $TODAY, Yesterday: $YESTERDAY"
          if [ -n "$SRC_TODAY" ] && [ -f "$SRC_TODAY" ]; then
            echo "Found today's file: $SRC_TODAY"
            echo "source_file=$SRC_TODAY" >> $GITHUB_OUTPUT
          elif [ -n "$SRC_YESTERDAY" ] && [ -f "$SRC_YESTERDAY" ]; then
            echo "Today's file not found. Found yesterday's file: $SRC_YESTERDAY"
            echo "source_file=$SRC_YESTERDAY" >> $GITHUB_OUTPUT
          else
            echo "Error: Neither today's nor yesterday's article file exists."
            exit 1
          fi

      - name: Copy article file to VuePress docs
        if: steps.determine_src.outputs.source_file != ''
        run: |
          DST_FILE="modules/news-vuepress-docs/docs/today/today-news-summary.md"
          echo "Copying file '${{ steps.determine_src.outputs.source_file }}' to ${DST_FILE}"
          cp "${{ steps.determine_src.outputs.source_file }}" "$DST_FILE"

      - name: Set up Git identity
        run: |
          git config --global user.name "fox142857"
          git config --global user.email "fox142857@foxmail.com"

      - name: Commit and push copied article summary
        run: |
          git add -f modules/news-vuepress-docs/docs/today/today-news-summary.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update today's news summary article [skip ci]"
            git push origin master
          fi

      - name: Trigger email alert for Copy News Article result
        if: always()
        run: |
          WORKFLOW_FILE="06-copy-news-article.yml"
          if [ "${{ job.status }}" = "Success" ]; then
            ORIGINAL_SUBJECT="${WORKFLOW_FILE}: Copy News Article succeeded"
            CLASSIFICATION="Info"
            DETAIL="Result: The article file was successfully copied to the VuePress docs."
          else
            ORIGINAL_SUBJECT="${WORKFLOW_FILE}: Copy News Article failed"
            CLASSIFICATION="Warn"
            DETAIL="Result: The article file copying process encountered an error. Please check logs."
          fi
          FINAL_SUBJECT="Workflow Alert: ${CLASSIFICATION}"
          FINAL_BODY="${WORKFLOW_FILE}\n${ORIGINAL_SUBJECT}\n${DETAIL}"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d "{\"event_type\": \"send-email-alert\", \"client_payload\": {\"subject\": \"${FINAL_SUBJECT}\", \"body\": \"${FINAL_BODY}\"}}"

      - name: Trigger Deploy workflow
        if: ${{ job.status == 'Success' }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "deploy-trigger"}'
