name: Consistency Checker

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  consistency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GH_TOKEN }}
          path: master_branch

      - name: Checkout crawler-service branch
        uses: actions/checkout@v3
        with:
          ref: crawler-service
          token: ${{ secrets.GH_TOKEN }}
          path: crawler_branch

      - name: Compare output directories
        id: diff_check
        continue-on-error: true
        run: |
          diff -qr master_branch/modules/news-crawler-service/src/output/ crawler_branch/modules/news-crawler-service/src/output/

      - name: Trigger email alert with comparison result
        run: |
          WORKFLOW_FILE="consistency-checker.yml"
          if [ "${{ steps.diff_check.outcome }}" = "success" ]; then 
            ORIGINAL_SUBJECT="${WORKFLOW_FILE}: Output directories are consistent"
            CLASSIFICATION="Info"
            DETAIL="Result: The output directories in the master and crawler-service branches are identical."
          else
            ORIGINAL_SUBJECT="${WORKFLOW_FILE}: Output directories mismatch"
            CLASSIFICATION="Error"
            DETAIL="Result: The output directories in the master and crawler-service branches are inconsistent. Please check the crawler output."
          fi
          FINAL_SUBJECT="Workflow Alert: ${CLASSIFICATION}"
          FINAL_BODY="${WORKFLOW_FILE}\n${ORIGINAL_SUBJECT}\n${DETAIL}"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d "{\"event_type\": \"send-email-alert\", \"client_payload\": {\"subject\": \"${FINAL_SUBJECT}\", \"body\": \"${FINAL_BODY}\"}}"
