name: file-checker-ai-summarize

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check-ai-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Check for AI Summarize Markdown file with today's date
        id: check_ai
        shell: bash
        run: |
          export TZ='Asia/Shanghai'
          TODAY=$(date +'%Y%m%d')
          echo "Today is: $TODAY"
          AI_FILE=$(ls modules/news-crawler-service/src/output/${TODAY}-[0-9][0-9][0-9][0-9]-ai-summarize.md 2>/dev/null || true)
          if [ -n "$AI_FILE" ]; then
            echo "Found file: $AI_FILE"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "AI Summarize file not found for pattern: ${TODAY}-[0-9][0-9][0-9][0-9]-ai-summarize.md"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Send email alert for AI Summarize file check result
        run: |
          WORKFLOW_FILE="file-checker-ai-summarize.yml"
          if [ "${{ steps.check_ai.outputs.exists }}" = "true" ]; then
            ORIGINAL_SUBJECT="${WORKFLOW_FILE}: AI Summarize file exists"
            CLASSIFICATION="Info"
            DETAIL="Result: The AI Summarize file with today's date is present."
          else
            ORIGINAL_SUBJECT="${WORKFLOW_FILE}: AI Summarize file missing"
            CLASSIFICATION="Warn"
            DETAIL="Result: The AI Summarize file with today's date is missing."
          fi
          FINAL_SUBJECT="Workflow Alert: ${CLASSIFICATION}"
          FINAL_BODY="${WORKFLOW_FILE}\n${ORIGINAL_SUBJECT}\n${DETAIL}"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d "{\"event_type\": \"send-email-alert\", \"client_payload\": {\"subject\": \"${FINAL_SUBJECT}\", \"body\": \"${FINAL_BODY}\"}}"
